# Generated by Django 3.0.5 on 2020-04-08 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('hire_date', models.DateField()),
                ('working_age', models.IntegerField()),
                ('rating_wage_per_hour', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('type_expense', models.CharField(choices=[('1', 'paid_salary')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Working_time',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('from_beforenoon', models.DateTimeField()),
                ('to_beforenoon', models.DateTimeField()),
                ('from_afternoon', models.DateTimeField()),
                ('to_afternoon', models.DateTimeField()),
                ('normal_wage', models.FloatField()),
                ('ot_wage', models.FloatField()),
                ('total_wage', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Paid_salary',
            fields=[
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.Expense')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Employee')),
            ],
        ),
    ]
