# Generated by Django 3.0.5 on 2020-04-14 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('hire_date', models.DateField()),
                ('working_age', models.IntegerField()),
                ('rating_wage_per_hour', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('type_expense', models.CharField(choices=[('1', 'paid_salary'), ('2', 'others')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('type_revenue', models.CharField(choices=[('1', 'ขายผ้าจากคลัง'), ('2', 'รับจ้างย้อม')], max_length=1)),
                ('date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Engaging',
            fields=[
                ('revenue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.Revenue')),
            ],
        ),
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('revenue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.Revenue')),
            ],
        ),
        migrations.CreateModel(
            name='Working_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_beforenoon', models.TimeField(blank=True, null=True)),
                ('to_beforenoon', models.TimeField(blank=True, null=True)),
                ('from_afternoon', models.TimeField(blank=True, null=True)),
                ('to_afternoon', models.TimeField(blank=True, null=True)),
                ('normal_wage', models.FloatField()),
                ('ot_wage', models.FloatField()),
                ('total_wage', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Employee')),
            ],
            options={
                'unique_together': {('date', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='Sell_list',
            fields=[
                ('list_no', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('cloth_in_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.Cloth_in_stock')),
                ('selling_revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Selling')),
            ],
        ),
        migrations.CreateModel(
            name='Paid_salary',
            fields=[
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.Expense')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Engage_list',
            fields=[
                ('list_no', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('cloth_in_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.Cloth_in_stock')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.Color')),
                ('engaging_revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Selling')),
            ],
        ),
    ]
