# Generated by Django 3.0.5 on 2020-04-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='engage_list',
            name='list_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Customer'),
        ),
        migrations.AlterField(
            model_name='sell_list',
            name='list_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
