# Generated by Django 3.0.5 on 2020-04-08 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0003_cloth_in_stock_cloth_type_color'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('type_revenue', models.CharField(choices=[('1', 'selling'), ('2', 'engaging')], max_length=1)),
                ('date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('revenue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.Revenue')),
            ],
        ),
        migrations.CreateModel(
            name='Sell_list',
            fields=[
                ('list_no', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('cloth_in_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.Cloth_in_stock')),
                ('selling_revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Selling')),
            ],
        ),
    ]
