# Generated by Django 3.0.5 on 2020-04-16 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
        ('account', '0002_auto_20200416_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engage_list',
            name='cloth_in_stock',
        ),
        migrations.AddField(
            model_name='engage_list',
            name='cloth_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloth.Cloth_type'),
        ),
        migrations.AlterField(
            model_name='engage_list',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloth.Color'),
        ),
        migrations.AlterField(
            model_name='engage_list',
            name='engaging_revenue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Engaging'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
