# Generated by Django 3.0.5 on 2020-04-08 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0003_cloth_in_stock_cloth_type_color'),
        ('account', '0002_customer_revenue_sell_list_selling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engaging',
            fields=[
                ('revenue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.Revenue')),
            ],
        ),
        migrations.CreateModel(
            name='Engage_list',
            fields=[
                ('list_no', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('cloth_in_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.Cloth_in_stock')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.Color')),
                ('engaging_revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Selling')),
            ],
        ),
    ]
