# Generated by Django 3.0.5 on 2020-04-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_engage_list_engaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_time',
            name='from_afternoon',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='working_time',
            name='from_beforenoon',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='working_time',
            name='to_afternoon',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='working_time',
            name='to_beforenoon',
            field=models.TimeField(),
        ),
    ]
