# Generated by Django 3.0.5 on 2020-04-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200411_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_time',
            name='from_afternoon',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='working_time',
            name='to_afternoon',
            field=models.TimeField(null=True),
        ),
    ]
