# Generated by Django 3.0.5 on 2020-04-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200411_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type_expense',
            field=models.CharField(choices=[('1', 'paid_salary'), ('2', 'others')], max_length=1),
        ),
        migrations.AlterField(
            model_name='working_time',
            name='from_beforenoon',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='working_time',
            name='to_beforenoon',
            field=models.TimeField(null=True),
        ),
    ]
