# Generated by Django 3.0.5 on 2020-04-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200417_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_time',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_times', to='account.Employee'),
        ),
    ]
