# Generated by Django 3.0.5 on 2020-04-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200411_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_time',
            name='from_afternoon',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='working_time',
            name='from_beforenoon',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='working_time',
            name='to_afternoon',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='working_time',
            name='to_beforenoon',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
