# Generated by Django 3.0.5 on 2020-04-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0003_auto_20200419_1849'),
        ('account', '0006_auto_20200417_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_list',
            name='cloth_in_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloth_sell', to='cloth.Cloth_in_stock'),
        ),
    ]
