# Generated by Django 3.0.5 on 2020-04-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200411_1549'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='working_time',
            unique_together={('date', 'employee')},
        ),
    ]
