# Generated by Django 3.0.5 on 2020-04-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200411_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='type_revenue',
            field=models.CharField(choices=[('1', 'ขายผ้าจากคลัง'), ('2', 'รับจ้างย้อม')], max_length=1),
        ),
    ]
