# Generated by Django 3.0.5 on 2020-04-14 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cloth_desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='../decoration/image')),
            ],
        ),
        migrations.CreateModel(
            name='Cloth_in_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('cloth_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.Cloth_type')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.Color')),
            ],
        ),
    ]
