# Generated by Django 3.0.5 on 2020-04-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paid_salary',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='paid_salary',
            name='expense',
        ),
        migrations.AlterUniqueTogether(
            name='working_time',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='working_time',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Paid_salary',
        ),
        migrations.DeleteModel(
            name='Working_time',
        ),
    ]
